name: Auto Deploy on release prereleased

on:
  release:
    types: [prereleased]

jobs:

  job-on-release-prereleased:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat << OBJECT
        ${{ toJson(github) }}
        OBJECT