name: Auto Deploy on release created

on:
  release:
    types: [created]

jobs:

  job-on-release-created:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat << OBJECT
        ${{ toJson(github) }}
        OBJECT