name: Deployment steps

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:

  deploy-common-code:
    runs-on: ubuntu-latest
    steps:
    - name: Echo target environment
      run: echo Deploying to $ENVIRONMENT
